export interface IPaper {
  id: number;
  created_at: string;
  name: string;
  magazine: string;
  position: number;
  side: string;
}

export const PaperOptions = [
  'Acácia Carmel',
  'Acácia Volcano',
  'Alpaca',
  'Ameixa Negra',
  'Ateliê',
  'Atenna',
  'Áureo',
  'Autentic',
  'Azul Sereno',
  'Beige',
  'Beton',
  'Branco Supremo',
  'Búfalo',
  'Cacao',
  'Cafelatte',
  'Camelo',
  'Canela',
  'Canelato',
  'Carvalho',
  'Carvalho Americano',
  'Carvalho Dakar',
  'Carvalho Mel',
  'Castanha Branca',
  'Castanheira Natural',
  'Castanho',
  'Ciliegio',
  'Cinza Cristal',
  'Cinza Puro',
  'Cinzell',
  'Concreto Decor',
  'Connect',
  'Cosmo',
  'Cumaru',
  'Damasco',
  'Deva',
  'Ébano',
  'Elmo Suíço',
  'Escarlate',
  'Farm',
  'Flor de Algodão',
  'Frapê',
  'Gaia',
  'Galês',
  'Grafito',
  'Gris',
  'Hidrófugo Branco',
  'Ipê Amarelo',
  'Jatobá Brasileiro',
  'Jequitibá',
  'Kashmir',
  'Linho',
  'Lino',
  'Lino Piombo',
  'Lord',
  'Louro Freijó',
  'Mezzo Bianco',
  'Noce Naturale',
  'Nogal Terracota',
  'Nogueira',
  'Nogueira Pecan',
  'Nogueira Persa',
  'Nordic',
  'Nova Imbuia',
  'Nude',
  'Pau-ferro',
  'Reali',
  'Rícori Nativo',
  'Sal Rosa',
  'Sálvia',
  'Sucupira',
  'Tabaco',
  'Taj',
  'Teka Ártico',
  'Tinto',
  'Titan',
  'Tokai',
  'Verde Jade',
  'Vesúvio',
  'Western',
];
